// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8QgE1gDXym2ufJytnGPb16wffiEjiyE',
    appId: '1:594624636719:web:864c08132efab257e063da',
    messagingSenderId: '594624636719',
    projectId: 'ecommercealmacen-3961e',
    authDomain: 'ecommercealmacen-3961e.firebaseapp.com',
    storageBucket: 'ecommercealmacen-3961e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVrAEJ9ue7UzwNiyUOOWwODFPNN1ZY5k',
    appId: '1:594624636719:android:d8c083197ff5a722e063da',
    messagingSenderId: '594624636719',
    projectId: 'ecommercealmacen-3961e',
    storageBucket: 'ecommercealmacen-3961e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2cjs7nHCM1krSLrCvfeRyXTmV3xnnAiA',
    appId: '1:594624636719:ios:aeeed1a7f32c610ee063da',
    messagingSenderId: '594624636719',
    projectId: 'ecommercealmacen-3961e',
    storageBucket: 'ecommercealmacen-3961e.appspot.com',
    iosBundleId: 'com.example.frontendthelastcastle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2cjs7nHCM1krSLrCvfeRyXTmV3xnnAiA',
    appId: '1:594624636719:ios:0b88b059b5c70fd7e063da',
    messagingSenderId: '594624636719',
    projectId: 'ecommercealmacen-3961e',
    storageBucket: 'ecommercealmacen-3961e.appspot.com',
    iosBundleId: 'com.example.frontendthelastcastle.RunnerTests',
  );
}
